package agentdb

import (
	"net"
	"testing"
)

func TestClassifyIP(t *testing.T) {
	tests := []struct {
		name    string
		ip      net.IP
		private bool
	}{
		// Private/reserved IPs — should return true
		{"rfc1918 10.x", net.ParseIP("10.0.0.1"), true},
		{"rfc1918 172.16.x", net.ParseIP("172.16.0.1"), true},
		{"rfc1918 192.168.x", net.ParseIP("192.168.1.1"), true},
		{"rfc6598 cgnat", net.ParseIP("100.64.0.1"), true},
		{"loopback", net.ParseIP("127.0.0.1"), true},
		{"link-local", net.ParseIP("169.254.1.1"), true},
		{"nil ip", nil, true},
		{"ipv6 ULA", net.ParseIP("fd00::1"), true},

		// Public IPs — should return false
		{"google dns", net.ParseIP("8.8.8.8"), false},
		{"cloudflare dns", net.ParseIP("1.1.1.1"), false},
		{"test-net-3", net.ParseIP("203.0.113.1"), false},
		{"ipv6 public", net.ParseIP("2001:db8::1"), false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := classifyIP(tt.ip)
			if got != tt.private {
				t.Errorf("classifyIP(%v) = %v, want %v", tt.ip, got, tt.private)
			}
		})
	}
}

func TestDeriveNetworkType(t *testing.T) {
	tests := []struct {
		name      string
		publicIPs []string
		gateway   string
		want      string
	}{
		{"direct public", []string{"203.0.113.1"}, "192.168.1.1", "direct_public"},
		{"direct public no gateway", []string{"8.8.8.8"}, "", "direct_public"},
		{"nat likely", nil, "192.168.1.1", "nat_likely"},
		{"nat likely empty public", []string{}, "10.0.0.1", "nat_likely"},
		{"no external", nil, "", "no_external"},
		{"no external empty both", []string{}, "", "no_external"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := deriveNetworkType(tt.publicIPs, tt.gateway)
			if got != tt.want {
				t.Errorf("deriveNetworkType(%v, %q) = %q, want %q",
					tt.publicIPs, tt.gateway, got, tt.want)
			}
		})
	}
}

func TestParseResolvConf(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    []string
	}{
		{
			"standard two nameservers",
			"# Generated by NetworkManager\nnameserver 8.8.8.8\nnameserver 8.8.4.4\nsearch example.com\n",
			[]string{"8.8.8.8", "8.8.4.4"},
		},
		{
			"comments and empty lines",
			"# comment\n\nnameserver 1.1.1.1\n# another comment\nnameserver 9.9.9.9\n\n",
			[]string{"1.1.1.1", "9.9.9.9"},
		},
		{
			"empty content",
			"",
			nil,
		},
		{
			"no nameserver lines",
			"# just comments\nsearch example.com\ndomain example.com\n",
			nil,
		},
		{
			"trailing whitespace",
			"nameserver 8.8.8.8  \nnameserver 8.8.4.4\t\n",
			[]string{"8.8.8.8", "8.8.4.4"},
		},
		{
			"ipv6 nameserver",
			"nameserver 2001:4860:4860::8888\nnameserver 8.8.8.8\n",
			[]string{"2001:4860:4860::8888", "8.8.8.8"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := parseResolvConf(tt.content)
			if len(got) != len(tt.want) {
				t.Fatalf("parseResolvConf() returned %d entries, want %d\ngot:  %v\nwant: %v",
					len(got), len(tt.want), got, tt.want)
			}
			for i := range got {
				if got[i] != tt.want[i] {
					t.Errorf("entry[%d] = %q, want %q", i, got[i], tt.want[i])
				}
			}
		})
	}
}

func TestParseLinuxRoute(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{
			"standard default gateway",
			"Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT\n" +
				"eth0\t00000000\t0101A8C0\t0003\t0\t0\t100\t00000000\t0\t0\t0\n" +
				"eth0\t0001A8C0\t00000000\t0001\t0\t0\t100\t00FFFFFF\t0\t0\t0\n",
			"192.168.1.1",
		},
		{
			"multiple interfaces one default",
			"Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT\n" +
				"eth1\t0A0A0A00\t00000000\t0001\t0\t0\t100\t00FFFFFF\t0\t0\t0\n" +
				"eth0\t00000000\t0100000A\t0003\t0\t0\t100\t00000000\t0\t0\t0\n",
			"10.0.0.1",
		},
		{
			"empty content",
			"",
			"",
		},
		{
			"header only",
			"Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT\n",
			"",
		},
		{
			"no default route",
			"Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT\n" +
				"eth0\t0001A8C0\t00000000\t0001\t0\t0\t100\t00FFFFFF\t0\t0\t0\n" +
				"eth0\t0A000000\t00000000\t0001\t0\t0\t100\t00FF0000\t0\t0\t0\n",
			"",
		},
		{
			"gateway 10.0.0.1 hex little-endian",
			"Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT\n" +
				"eth0\t00000000\t0100000A\t0003\t0\t0\t0\t00000000\t0\t0\t0\n",
			"10.0.0.1",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := parseLinuxRoute(tt.content)
			if got != tt.want {
				t.Errorf("parseLinuxRoute() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestParseDarwinRoute(t *testing.T) {
	tests := []struct {
		name   string
		output string
		want   string
	}{
		{
			"standard output",
			"   route to: default\n" +
				"destination: default\n" +
				"       mask: default\n" +
				"    gateway: 192.168.1.1\n" +
				"  interface: en0\n" +
				"      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING,AUTOCONF>\n",
			"192.168.1.1",
		},
		{
			"empty output",
			"",
			"",
		},
		{
			"no gateway line",
			"   route to: default\n" +
				"destination: default\n" +
				"  interface: en0\n",
			"",
		},
		{
			"link-layer gateway not ip",
			"   route to: default\n" +
				"destination: default\n" +
				"    gateway: link#4\n" +
				"  interface: en0\n",
			"",
		},
		{
			"ipv6 gateway",
			"   route to: default\n" +
				"    gateway: fe80::1\n" +
				"  interface: en0\n",
			"fe80::1",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := parseDarwinRoute(tt.output)
			if got != tt.want {
				t.Errorf("parseDarwinRoute() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestParseWindowsRoute(t *testing.T) {
	tests := []struct {
		name   string
		output string
		want   string
	}{
		{
			name: "standard output",
			output: `===========================================================================
Interface List
  6...00 15 5d 01 02 03 ......Microsoft Hyper-V Network Adapter
===========================================================================
IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.1.1    192.168.1.100     25
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
===========================================================================`,
			want: "192.168.1.1",
		},
		{
			name:   "empty output",
			output: "",
			want:   "",
		},
		{
			name: "no default route",
			output: `Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331`,
			want: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := parseWindowsRoute(tt.output)
			if got != tt.want {
				t.Errorf("parseWindowsRoute() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestParseWindowsDNS(t *testing.T) {
	tests := []struct {
		name   string
		output string
		want   []string
	}{
		{
			name: "single DNS server",
			output: `Windows IP Configuration

   Host Name . . . . . . . . . . . . : DESKTOP-ABC
   DNS Servers . . . . . . . . . . . : 8.8.8.8

Ethernet adapter Ethernet:`,
			want: []string{"8.8.8.8"},
		},
		{
			name: "multiple DNS servers with continuation",
			output: `   DNS Servers . . . . . . . . . . . : 8.8.8.8
                                       8.8.4.4
                                       1.1.1.1

   NetBIOS over Tcpip. . . . . . . . : Enabled`,
			want: []string{"8.8.8.8", "8.8.4.4", "1.1.1.1"},
		},
		{
			name:   "empty output",
			output: "",
			want:   nil,
		},
		{
			name: "no DNS section",
			output: `Windows IP Configuration

   Host Name . . . . . . . . . . . . : DESKTOP-ABC`,
			want: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := parseWindowsDNS(tt.output)
			if len(got) != len(tt.want) {
				t.Fatalf("parseWindowsDNS() = %v (len %d), want %v (len %d)", got, len(got), tt.want, len(tt.want))
			}
			for i, g := range got {
				if g != tt.want[i] {
					t.Errorf("parseWindowsDNS()[%d] = %q, want %q", i, g, tt.want[i])
				}
			}
		})
	}
}
