FROM ubuntu

# Install OpenSSH Server
RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create required directory for SSH
RUN mkdir /var/run/sshd

# Set root password for SSH (you should change this in production)
RUN echo 'root:password' | chpasswd

# SSH login fix. Otherwise user is kicked off after login
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH access fix
RUN sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd

# Expose port 22
EXPOSE 22

# Start SSH service
CMD ["/usr/sbin/sshd", "-D"]
